version: '3.8'

services:
  web:
    build:
      context: .
    environment:
      FLASK_APP: dogecoinisawesome.py
      FLASK_ENV: development
    ports:
      - 5000:5000
    volumes:
      - ./:/app
